name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - gh-pages

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup black environment
        run: conda create --quiet --name black pyflakes

      - name: Check Spelling
        uses: crate-ci/typos@7ad296c72fa8265059cc03d1eda562fbdfcd6df2 # v1.9.0
        with:
          files: ./docs/getting_started/ ./docs/index.rst

      - name: Lint and format Python code
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black
          pip install -r .github/dev-requirements.txt
          pre-commit run --all-files

  testing:
    needs: formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup testing environment
        run: conda create --quiet --name testing pytest

      - name: Test caliper
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate testing
          pip install -e .[all]
          pytest -sv tests/*.py
          /bin/bash tests/test_client.sh
