name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - gh-pages 

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup black environment
        run: conda create --quiet --name black pyflakes

      - name: Check formatting with black
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black
          pip install black==20.8b1
          black --check caliper

      - name: Check imports with pyflakes
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black
          pyflakes caliper

  testing:
    needs: formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup testing environment
        run: conda create --quiet --name testing pytest

      - name: Test caliper
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate testing
          pip install -e .[all]
          pytest -sv tests/*.py
          /bin/bash tests/test_client.sh
